### ISSUE TITLE
Can't locate DDP.pm in @INC

### ISSUE THREAD

**Issue by eserte** [rawleyfowler/Dancer2-Controllers#1]
The test suite fails if DDP.pm is not installed --- probably a missing prereq declaration. A sample fail report: http://www.cpantesters.org/cpan/report/953957a4-d4d4-11ee-b213-832a6e8775ea

**Comment by rawleyfowler** [comment]
Thanks, I forgot to remove DDP while debugging. I have published a new version. Thanks!
